### PR TITLE
Conflicts with slim 3.x series

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by Nyholm** [comment]
Why is it in conflict with Slim 3.x?

**Comment by harikt** [comment]
Hey @Nyholm 

I have installed slim/slim 3.x, and was testing the http-interop/http-factory-slim for a test project .

The http-interop/http-factory-slim installs `slim/http` which is for 4.x . 

So composer have hard time to understand which one is `Slim\Http\Response` or `Slim\Http\Request` .

See https://github.com/slimphp/Slim/blob/c138554cb16a92156db787143ab1f266dece7c7f/Slim/Http/Request.php#L138  , https://github.com/slimphp/Slim-Http/blob/3d0c5ba727c2c70dbf49138671fc4e1e3e8d196b/src/Request.php#L175 .

These classes are entirely different and have different methods to which I have pointed.

Please do see https://github.com/slimphp/Slim/pull/2152

**Comment by tuupola** [comment]
Slim 3 itself does not use `slim/http` even though it was extracted from there. Installing both `slim/http` and `slim/slim` seems to cause problems.

https://github.com/slimphp/Slim-Http/tree/master/src
https://github.com/slimphp/Slim/tree/3.x/Slim/Http

**Comment by Nyholm** [comment]
Okey. So:
`slim/slim` 3.x has a class called `Slim\Http\Request` which is PSR-7. 
`slim/http` does also have the class `Slim\Http\Request` which also is PSR-7. 

This library is created for `slim/http` (as it is in our composer.json). If you pull down slim/slim:3.x you will get two classes with the same namespace.

**Review by Nyholm — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you @harikt  and @tuupola

**Comment by tuupola** [comment]
I started a discussion about this in Slim Slack since AFAIK `slim/http` is in bit of a limbo at the moment. So either `http-interop/http-factory-slim` should use `slim/slim` or `slim/slim` itself should actually use PSR-7 implementation from `slim/http`.

Currently it seems you cannot use both  `slim/http` and  `slim/slim` at the same time.

**Pull request merged**
