### PR TITLE
Update dependencies and tests

### PR DESCRIPTION
**Pull request by sagikazarmark**
Blocked by http-interop/http-factory-tests#19 and http-interop/http-factory-tests#20

### CODE REVIEW

**Review by shadowhand — APPROVED** [review]

**Comment by sagikazarmark** [comment]
Ready

**Comment by shadowhand** [comment]
Looks like this needs an update to the factories: https://travis-ci.org/http-interop/http-factory-slim/jobs/183948383

**Review by shadowhand — CHANGES_REQUESTED** [review]
Implementing classes are out of sync with interfaces.

https://travis-ci.org/http-interop/http-factory-slim/jobs/183948383

**Comment by shadowhand** [comment]
Looks like some of these tests need `@backupGlobals` to prevent loss of data that PHPUnit needs.

**Comment by sagikazarmark** [comment]
Implementation updated, tests are passing.

**Review by shadowhand — APPROVED** [review]

**Comment by shadowhand** [comment]
This has been tagged in 0.1.0.

**Pull request merged**
